# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.workers.max=16
android.enableAapt2Jvmargs=-Xmx2048m
android.nonTransitiveRClass=true
android.useAndroidX=true

# Architecture & Engine
newArchEnabled=true
hermesEnabled=true

# Signing Config (UPDATED TO MATCH YOUR ACTUAL FILE)
MYAPP_UPLOAD_STORE_FILE=my-release-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=my-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=voltrify2412
MYAPP_UPLOAD_KEY_PASSWORD=voltrify2412